import type { Metadata } from "next";

import "./globals.css";


import {
  antonio,
  quicksand,
  sen,
  syne,
  archivoBlack,
  poppins,
  sedan,
} from '@components/app/Fonts'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
         className={`${antonio.variable} ${quicksand.variable} ${sen.variable} ${syne.variable} ${archivoBlack.variable} ${poppins.variable} ${sedan.variable} bg-black text-white overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
